<?php
	$meta = '';
	$styles = "<link rel='stylesheet' href='" . get_stylesheet_directory_uri() . "/immersive-stories/css/common.css' type='text/css' media='all' />";
	$scripts = "<script src='" . get_stylesheet_directory_uri() . "/campaign/js/animationLibraries.min.js' type='text/javascript'></script>
<script src='" . get_stylesheet_directory_uri() . "/campaign/js/header.js' type='text/javascript'></script>";
	get_header( "campaign-v2" );
?>
<div id="immersive-body">
	<main id="main_content">
		<section class="text-block">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 copy ">
						<div style="text-align: center">
							<h2 class="headline-gold">What you care about <br />can change the world</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vehicula arcu at consequat euismod. Donec iaculis mi in arcu tempus, nec faucibus odio tempus. Maecenas tincidunt fringilla velit, vitae suscipit enim vulputate id. Morbi eu ullamcorper odio, et vulputate eros. Aliquam mauris nulla, faucibus vel feugiat vitae, vehicula at leo. Sed at bibendum justo. Phasellus vitae sollicitudin ante, vel posuere magna. Nam fringilla vehicula massa, sed egestas nisi hendrerit non. Fusce velit nunc, fringilla ac placerat eget, tristique viverra purus. Donec porta nisl sit amet ante varius, eget sollicitudin magna tristique. Suspendisse accumsan tortor vel sapien vulputate varius. Nulla nec sagittis magna. Nulla facilisi. Sed ut ipsum eu velit molestie posuere. Suspendisse nec consequat neque, ac eleifend leo. Praesent tortor quam, maximus a mi a, luctus accumsan nibh.</p>
							<p>Suspendisse nunc augue, placerat vel mi a, accumsan volutpat metus. Nulla facilisi. Etiam et consectetur urna. Nunc eros lorem, sollicitudin eget cursus a, dictum non quam. Quisque tortor erat, iaculis in hendrerit vitae, scelerisque vel elit. Aenean lacus nibh, egestas sed tristique nec, elementum quis felis. Pellentesque efficitur scelerisque diam, in hendrerit dolor scelerisque id. Nullam tempor porttitor lorem, ac suscipit enim venenatis in. Nunc varius urna sed arcu facilisis, vel scelerisque enim placerat. Duis non tristique lorem. Donec sed luctus nulla, a accumsan lorem.</p>
							<p>Quisque non bibendum sapien. Donec feugiat pulvinar nisi, sed rhoncus justo lacinia non. Maecenas sodales, tellus quis eleifend varius, nunc quam tincidunt ligula, eget eleifend dolor quam nec eros. Sed a mi sapien. Donec eget odio eget nunc lobortis viverra in sed lorem. Donec nec turpis nulla. Nam ligula justo, interdum eget diam et, pharetra luctus metus. Etiam lacinia at magna sed sodales. Mauris vel augue consequat, iaculis ligula vitae, pellentesque turpis. Donec mollis erat sit amet nisi rhoncus, suscipit ultricies ligula vestibulum. Nullam nec magna bibendum, blandit eros eu, tincidunt quam. Cras non malesuada orci. Vestibulum ultrices, tortor vitae volutpat ullamcorper, orci urna condimentum orci, vitae varius velit risus sed nisi. Integer ut urna ac nisl consectetur convallis.</p>
							<p>Sed pretium neque sed cursus facilisis. Nam pretium gravida porttitor. Etiam in ligula laoreet, fermentum nunc eget, auctor purus. Nunc vel metus ac sapien venenatis vehicula vitae ut diam. Vivamus a augue consequat nisl consequat vestibulum. Fusce rhoncus ullamcorper lectus, sed scelerisque quam gravida non. Praesent pulvinar dignissim nisi, sed aliquet erat consequat nec. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras laoreet commodo arcu. Pellentesque iaculis elit purus, non pulvinar turpis maximus a. Sed pellentesque lacinia risus, vitae porta ipsum tempor non.</p>
							<p>Nam nec vestibulum neque, non aliquam tortor. Nam sollicitudin nunc ipsum, sed volutpat mi bibendum pharetra. Mauris sodales lacus nulla. Fusce sit amet euismod tellus, id condimentum enim. Donec in hendrerit lorem. Morbi dictum, erat non tempor accumsan, ipsum odio condimentum lectus, at porttitor nibh nunc consequat nisi. Aliquam bibendum sapien sed sapien egestas, et rhoncus neque placerat. Morbi id urna congue, suscipit enim eget, laoreet nisl.</p>
							<p>Sed a posuere neque. Quisque ac facilisis sem, a finibus nisl. Fusce vitae massa et mi pulvinar pellentesque quis sit amet turpis. Nunc eget justo quis magna condimentum malesuada. Ut ligula nulla, egestas ac mollis ut, sodales imperdiet nulla. Nam convallis eu est volutpat bibendum. Phasellus ornare dolor ut est maximus interdum. Quisque nec sodales nisl. Fusce ex tortor, volutpat id feugiat id, laoreet vitae ex. Aliquam sollicitudin tellus non dignissim sodales. Aliquam eu lacus et sem semper luctus a vitae quam. Fusce vestibulum pellentesque aliquam. Quisque interdum arcu sed metus viverra consectetur.</p>
							<p>Morbi a dolor vel orci tincidunt euismod venenatis id tortor. Nulla facilisi. Integer porta auctor libero sed porta. Donec in risus ut dolor finibus pharetra nec quis lacus. Mauris ullamcorper efficitur nisi sed ullamcorper. Sed lobortis vel tortor ut elementum. Donec quam magna, accumsan sit amet turpis in, malesuada feugiat nisl. Vestibulum cursus urna ac nisi placerat, sit amet placerat ligula elementum.</p>
							<p>Sed tincidunt vulputate tristique. Donec risus nibh, dignissim sed consectetur a, egestas eu est. Quisque porttitor nec urna ultrices tempus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet libero imperdiet, elementum nisl eget, cursus quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras cursus sapien non lacus sagittis, ac tincidunt turpis placerat. Nulla in augue sem. Aliquam eleifend lectus eget felis rutrum facilisis. Etiam aliquam metus eu neque ullamcorper varius. Nam lorem odio, gravida quis lorem ac, consequat laoreet arcu.</p>
							<p>Aenean egestas ullamcorper sapien at porttitor. Phasellus lacinia, velit nec faucibus rutrum, mauris dolor vehicula nunc, id porttitor mauris dui gravida sem. Nulla sed luctus risus. Aliquam accumsan porta posuere. Proin id consectetur justo, eu viverra urna. Suspendisse potenti. Aenean dignissim diam vel molestie dapibus.</p>
							<p>Nulla convallis ligula et volutpat malesuada. Donec et ligula ut lectus vehicula molestie non sed arcu. Curabitur nec mi viverra, iaculis erat a, blandit nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris mattis semper molestie. Maecenas in turpis at augue efficitur pellentesque et eu mi. Vestibulum a sapien sit amet elit aliquam scelerisque eu eu massa. Nunc ac risus quis leo mollis aliquam. Pellentesque malesuada ligula enim, non tristique dui posuere vitae. Suspendisse a magna vel ex euismod cursus. Nunc pretium lorem fringilla justo iaculis rhoncus.</p>
							<div id="immersive-give-iframe"></div>
							<div class="boundless-button sm dark give"><span><a id="immersive-give" data-fund="AUPGEN,CBEIIN,LAPERU" href="#">Give now</a></span></div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</main>
</div>
<?php get_template_part('footer', 'campaign-v2'); ?>
